I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/first_mission.rpy", line 5, in script
    with pause(1)
  File "game/first_mission.rpy", line 5, in <module>
    with pause(1)
NameError: name 'pause' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/first_mission.rpy", line 5, in script
    with pause(1)
  File "C:\Users\Nitsan\Downloads\renpy-7.3.5-sdk\renpy-7.3.5-sdk\renpy\ast.py", line 1382, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\Nitsan\Downloads\renpy-7.3.5-sdk\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Nitsan\Downloads\renpy-7.3.5-sdk\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/first_mission.rpy", line 5, in <module>
    with pause(1)
NameError: name 'pause' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
 1.0
Thu Nov 12 14:09:39 2020
